version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: faction_dev
    volumes:
      - '/private/var/lib/postgresql:/var/lib/postgresql'

  redis:
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local